import 'package:hive/hive.dart';

part 'user_model.g.dart'; // This file will be generated by Hive

@HiveType(typeId: 1) // Ensure this typeId is unique among your models
class UserModel {
  @HiveField(0)
  String id;

  @HiveField(1)
  String username;

  @HiveField(2)
  String password;

  @HiveField(3)
  String salt;

  UserModel({
    required this.id,
    required this.username,
    required this.password,
    required this.salt
  });
}